=== thassae/votebem/schemas/perfil.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["id","papel","nomeCompleto","fotoUrl","partido","resumoBiografico"],
  "properties": {
    "id": { "type": "string" },
    "papel": { "type": "string", "enum": ["presidente","vice"] },
    "nomeCompleto": { "type": "string" },
    "nomeUrna": { "type": "string" },
    "cpf": { "type": "string" },
    "dataNascimento": { "type": "string" },
    "genero": { "type": "string" },
    "identidadeGenero": { "type": "string" },
    "orientacaoSexual": { "type": "string" },
    "corRaca": { "type": "string" },
    "etniaIndigena": { "type": "string" },
    "quilombola": { "type": "string" },
    "estadoCivil": { "type": "string" },
    "grauInstrucao": { "type": "string" },
    "ocupacao": { "type": "string" },
    "nacionalidadeNaturalidade": { "type": "string" },
    "partidoIsolado": { "type": "string" },
    "composicaoColigacao": { "type": "string" },
    "situacaoCandidatura": { "type": "string" },
    "urlTse": { "type": "string", "format": "uri" },
    "fotoUrl": { "type": "string" },
    "partido": { "type": "string" },
    "resumoBiografico": { "type": "string" },
    "formacao": { "type": "array", "items": { "type": "string" } },
    "cargosOcupados": { "type": "array", "items": { "type": "object", "properties": { "cargo": {"type":"string"}, "instituicao": {"type":"string"}, "periodo": {"type":"string"} }, "required": ["cargo","instituicao","periodo"], "additionalProperties": false } }
  },
  "additionalProperties": false
}

=== thassae/votebem/public/data/perfis.json
[
  {
    "id": "perfil-27-presidente",
    "papel": "presidente",
    "nomeCompleto": "CLARIANA ZACARKIM BARAO",
    "fotoUrl": "https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/20322002026/280002552484/BR",
    "partido": "DC",
    "resumoBiografico": "Advogada, com ensino superior completo.",
    "nomeUrna": "CLARIANA BARAO",
    "cpf": "015.421.491-42",
    "dataNascimento": "03/04/1987",
    "genero": "Feminino",
    "identidadeGenero": "Cisgenero",
    "orientacaoSexual": "Heterossexual",
    "corRaca": "Branca",
    "quilombola": "Nao",
    "estadoCivil": "Solteiro(a)",
    "grauInstrucao": "Superior Completo",
    "ocupacao": "Advogado",
    "nacionalidadeNaturalidade": "Brasileira Nata / MT-Cuiaba",
    "partidoIsolado": "DC",
    "composicaoColigacao": "Nao se aplica",
    "situacaoCandidatura": "Aguardando julgamento",
    "urlTse": "https://divulgacandcontas.tse.jus.br/divulga/#/candidato/BR/BR/20322002026/280002552484/2026/BR",
    "formacao": ["Superior completo"],
    "cargosOcupados": []
  },
  {
    "id": "perfil-27-vice",
    "papel": "vice",
    "nomeCompleto": "FABIANA CRISTINA TAVARES TORQUATO",
    "fotoUrl": "https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/20322002026/280002552485/BR",
    "partido": "DC",
    "resumoBiografico": "Advogada, com ensino superior completo.",
    "nomeUrna": "FABIANA TORQUATO",
    "cpf": "026.680.969-36",
    "dataNascimento": "04/07/1980",
    "genero": "Feminino",
    "orientacaoSexual": "Heterossexual",
    "corRaca": "Parda",
    "quilombola": "Nao",
    "estadoCivil": "Solteiro(a)",
    "grauInstrucao": "Superior Completo",
    "ocupacao": "Advogado",
    "nacionalidadeNaturalidade": "Brasileira Nata / SP-Pariquera-acu",
    "partidoIsolado": "DC",
    "composicaoColigacao": "Nao se aplica",
    "situacaoCandidatura": "Aguardando julgamento",
    "urlTse": "https://divulgacandcontas.tse.jus.br/divulga/#/candidato/BR/BR/20322002026/280002552485/2026/BR",
    "formacao": ["Superior completo"],
    "cargosOcupados": []
  },
  {
    "id": "perfil-21-presidente",
    "papel": "presidente",
    "nomeCompleto": "EDMILSON SILVA COSTA",
    "fotoUrl": "https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/20322002026/280002551975/BR",
    "partido": "PCB",
    "resumoBiografico": "Aposentado, com ensino superior completo.",
    "nomeUrna": "EDMILSON COSTA",
    "cpf": "044.976.433-87",
    "dataNascimento": "08/04/1950",
    "genero": "Masculino",
    "corRaca": "Parda",
    "quilombola": "Nao",
    "estadoCivil": "Solteiro(a)",
    "grauInstrucao": "Superior Completo",
    "ocupacao": "Aposentado (Exceto Servidor Publico)",
    "nacionalidadeNaturalidade": "Brasileira Nata / MA-Pedreiras",
    "partidoIsolado": "PCB",
    "composicaoColigacao": "Nao se aplica",
    "situacaoCandidatura": "Aguardando julgamento",
    "urlTse": "https://divulgacandcontas.tse.jus.br/divulga/#/candidato/BR/BR/20322002026/280002551975/2026/BR",
    "formacao": ["Superior completo"],
    "cargosOcupados": []
  },
  {
    "id": "perfil-21-vice",
    "papel": "vice",
    "nomeCompleto": "CLEUSA DOS SANTOS",
    "fotoUrl": "https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/20322002026/280002551976/BR",
    "partido": "PCB",
    "resumoBiografico": "Servidora pública civil aposentada, com ensino superior completo.",
    "nomeUrna": "CLEUSA SANTOS",
    "cpf": "019.934.798-05",
    "dataNascimento": "07/04/1956",
    "genero": "Feminino",
    "identidadeGenero": "Cisgenero",
    "corRaca": "Branca",
    "quilombola": "Nao",
    "estadoCivil": "Solteiro(a)",
    "grauInstrucao": "Superior Completo",
    "ocupacao": "Servidor Publico Civil Aposentado",
    "nacionalidadeNaturalidade": "Brasileira Nata / GO-Goiania",
    "partidoIsolado": "PCB",
    "composicaoColigacao": "Nao se aplica",
    "situacaoCandidatura": "Aguardando julgamento",
    "urlTse": "https://divulgacandcontas.tse.jus.br/divulga/#/candidato/BR/BR/20322002026/280002551976/2026/BR",
    "formacao": ["Superior completo"],
    "cargosOcupados": []
  },
  {
    "id": "perfil-70-presidente",
    "papel": "presidente",
    "nomeCompleto": "AUGUSTO JORGE CURY",
    "fotoUrl": "https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/20322002026/280002551547/BR",
    "partido": "AVANTE",
    "resumoBiografico": "Escritor e critico, com ensino superior completo.",
    "nomeUrna": "ESCRITOR AUGUSTO CURY",
    "cpf": "021.629.368-52",
    "dataNascimento": "02/10/1958",
    "genero": "Masculino",
    "identidadeGenero": "Cisgenero",
    "orientacaoSexual": "Heterossexual",
    "corRaca": "Branca",
    "quilombola": "Nao",
    "estadoCivil": "Casado(a)",
    "grauInstrucao": "Superior Completo",
    "ocupacao": "Escritor e Critico",
    "nacionalidadeNaturalidade": "Brasileira Nata / SP-Colina",
    "partidoIsolado": "AVANTE",
    "composicaoColigacao": "Nao se aplica",
    "situacaoCandidatura": "Aguardando julgamento",
    "urlTse": "https://divulgacandcontas.tse.jus.br/divulga/#/candidato/BR/BR/20322002026/280002551547/2026/BR",
    "formacao": ["Superior completo"],
    "cargosOcupados": []
  },
  {
    "id": "perfil-70-vice",
    "papel": "vice",
    "nomeCompleto": "JULIO CESAR DELGADO",
    "fotoUrl": "https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/20322002026/280002551546/BR",
    "partido": "AVANTE",
    "resumoBiografico": "Advogado, com ensino superior completo.",
    "nomeUrna": "JULIO DELGADO",
    "cpf": "819.933.586-68",
    "dataNascimento": "18/11/1966",
    "genero": "Masculino",
    "identidadeGenero": "Cisgenero",
    "orientacaoSexual": "Heterossexual",
    "corRaca": "Branca",
    "quilombola": "Nao",
    "estadoCivil": "Casado(a)",
    "grauInstrucao": "Superior Completo",
    "ocupacao": "Advogado",
    "nacionalidadeNaturalidade": "Brasileira Nata / MG-Juiz de Fora",
    "partidoIsolado": "AVANTE",
    "composicaoColigacao": "Nao se aplica",
    "situacaoCandidatura": "Aguardando julgamento",
    "urlTse": "https://divulgacandcontas.tse.jus.br/divulga/#/candidato/BR/BR/20322002026/280002551546/2026/BR",
    "formacao": ["Superior completo"],
    "cargosOcupados": []
  },
  {
    "id": "perfil-22-presidente",
    "papel": "presidente",
    "nomeCompleto": "FLAVIO NANTES BOLSONARO",
    "fotoUrl": "https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/20322002026/280002551544/BR",
    "partido": "PL",
    "resumoBiografico": "Senador, com ensino superior completo.",
    "nomeUrna": "FLAVIO BOLSONARO",
    "cpf": "087.011.227-97",
    "dataNascimento": "30/04/1981",
    "genero": "Masculino",
    "orientacaoSexual": "Heterossexual",
    "corRaca": "Branca",
    "quilombola": "Nao",
    "estadoCivil": "Casado(a)",
    "grauInstrucao": "Superior Completo",
    "ocupacao": "Senador",
    "nacionalidadeNaturalidade": "Brasileira Nata / RJ-Resende",
    "partidoIsolado": "PL",
    "composicaoColigacao": "Nao se aplica",
    "situacaoCandidatura": "Aguardando julgamento",
    "urlTse": "https://divulgacandcontas.tse.jus.br/divulga/#/candidato/BR/BR/20322002026/280002551544/2026/BR",
    "formacao": ["Superior completo"],
    "cargosOcupados": []
  },
  {
    "id": "perfil-22-vice",
    "papel": "vice",
    "nomeCompleto": "ALFREDO GASPAR DE MENDONCA NETO",
    "fotoUrl": "https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/20322002026/280002551543/BR",
    "partido": "PL",
    "resumoBiografico": "Deputado, com ensino superior completo.",
    "nomeUrna": "ALFREDO GASPAR",
    "cpf": "725.030.174-87",
    "dataNascimento": "13/08/1970",
    "genero": "Masculino",
    "orientacaoSexual": "Heterossexual",
    "corRaca": "Branca",
    "quilombola": "Nao",
    "estadoCivil": "Casado(a)",
    "grauInstrucao": "Superior Completo",
    "ocupacao": "Deputado",
    "nacionalidadeNaturalidade": "Brasileira Nata / AL-Maceio",
    "partidoIsolado": "PL",
    "composicaoColigacao": "Nao se aplica",
    "situacaoCandidatura": "Aguardando julgamento",
    "urlTse": "https://divulgacandcontas.tse.jus.br/divulga/#/candidato/BR/BR/20322002026/280002551543/2026/BR",
    "formacao": ["Superior completo"],
    "cargosOcupados": []
  },
  {
    "id": "perfil-16-presidente",
    "papel": "presidente",
    "nomeCompleto": "HERTZ DA CONCEICAO DIAS",
    "fotoUrl": "https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/20322002026/280002541457/BR",
    "partido": "PSTU",
    "resumoBiografico": "Professor de ensino fundamental, com ensino superior completo.",
    "nomeUrna": "HERTZ DIAS",
    "cpf": "428.058.133-91",
    "dataNascimento": "20/10/1970",
    "genero": "Masculino",
    "corRaca": "Preta",
    "etniaIndigena": "Nao Informada",
    "quilombola": "Nao",
    "estadoCivil": "Solteiro(a)",
    "grauInstrucao": "Superior Completo",
    "ocupacao": "Professor de Ensino Fundamental",
    "nacionalidadeNaturalidade": "Brasileira Nata / MA-Sao Jose de Ribamar",
    "partidoIsolado": "PSTU",
    "composicaoColigacao": "Nao se aplica",
    "situacaoCandidatura": "Aguardando julgamento",
    "urlTse": "https://divulgacandcontas.tse.jus.br/divulga/#/candidato/BR/BR/20322002026/280002541457/2026/BR",
    "formacao": ["Superior completo"],
    "cargosOcupados": []
  },
  {
    "id": "perfil-16-vice",
    "papel": "vice",
    "nomeCompleto": "VANESSA PORTUGAL BARBOSA",
    "fotoUrl": "https://divulgacandcontas.tse.jus.br/divulga/rest/arquivo/img/20322002026/280002541458/BR",
    "partido": "PSTU",
    "resumoBiografico": "Professora de ensino fundamental, com ensino superior completo.",
    "nomeUrna": "VANESSA PORTUGAL",
    "cpf": "787.984.776-68",
    "dataNascimento": "12/04/1970",
    "genero": "Feminino",
    "corRaca": "Branca",
    "etniaIndigena": "Nao Informada",
    "quilombola": "Nao",
    "estadoCivil": "Casado(a)",
    "grauInstrucao": "Superior Completo",
    "ocupacao": "Professor de Ensino Fundamental",
    "nacionalidadeNaturalidade": "Brasileira Nata / MG-Boa Esperanca",
    "partidoIsolado": "PSTU",
